<?php

namespace AppBundle\Repository;

/**
 * BatteryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BatteryRepository extends \Doctrine\ORM\EntityRepository
{
}
