<?php

namespace AppBundle\Repository;

/**
 * BatteryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BatteryCountRepository extends \Doctrine\ORM\EntityRepository
{
    public function getBatteries()
    {
        $queryBuilder = $this->getEntityManager()->createQueryBuilder('b');

        $queryBuilder
            ->select(['b.type','sum(b.count) as total'])
            ->from('AppBundle:BatteryCount','b')
            ->groupBy('b.type');

        return $queryBuilder->getQuery()->getResult();
    }
}
